# Generated by Django 4.2.2 on 2023-07-19 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='establecimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservas.establecimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='edificio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.edificio'),
        ),
    ]
