# Generated by Django 4.2.2 on 2023-07-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_aula_establecimiento_alter_aula_edificio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='equipamiento',
            field=models.ManyToManyField(blank=True, to='reservas.instrumento'),
        ),
    ]
