# Generated by Django 4.2.2 on 2023-07-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_aula_nombre_alter_edificio_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
