# Generated by Django 4.2.2 on 2023-07-19 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_aula_equipamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.establecimiento'),
        ),
    ]
