# Generated by Django 4.2.2 on 2023-07-29 02:30

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
