# Generated by Django 4.2.2 on 2023-07-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
