# Generated by Django 4.2.2 on 2023-07-19 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_aula_edificio_alter_aula_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='edificio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.edificio'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.establecimiento'),
        ),
    ]
