# Generated by Django 4.2.2 on 2023-07-19 02:35

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_aula_edificio_alter_aula_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='equipamiento_extra',
            field=models.ManyToManyField(blank=True, to='reservas.reservaequipamiento'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(fields=('nombre', 'establecimiento'), name='Sin aulas con el mismo nombre en un mismo establecimiento'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('hasta__lte', django.db.models.expressions.CombinedExpression(models.F('desde'), '+', models.Value(datetime.timedelta(seconds=3600))))), name='correct_datetime'),
        ),
    ]
