# Generated by Django 4.2.2 on 2023-07-19 02:37

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_reserva_equipamiento_extra_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='correct_datetime',
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('hasta__gte', django.db.models.expressions.CombinedExpression(models.F('desde'), '+', models.Value(datetime.timedelta(seconds=3600))))), name='correct_datetime'),
        ),
    ]
