# Generated by Django 4.2.2 on 2023-07-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_remove_reserva_correct_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipamientoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reservaequipamiento',
            name='instrumento',
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='correct_datetime',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='equipamiento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='equipamiento_extra',
        ),
        migrations.RenameModel(
            old_name='Instrumento',
            new_name='EquipamientoDisponible',
        ),
        migrations.DeleteModel(
            name='ReservaEquipamiento',
        ),
        migrations.AddField(
            model_name='equipamientoextra',
            name='equipamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.equipamientodisponible'),
        ),
        migrations.AddField(
            model_name='equipamientoextra',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.aula'),
        ),
    ]
