# Generated by Django 4.2.2 on 2023-07-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_equipamiento_equipamientoextra_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamiento',
            new_name='EquipamientoAula',
        ),
    ]
