# Generated by Django 4.2.2 on 2023-07-22 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_establecimiento_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEquipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.equipamientodisponible')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamiento', to='reservas.reserva')),
            ],
        ),
        migrations.AlterField(
            model_name='equipamientoaula',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamiento', to='reservas.aula'),
        ),
        migrations.DeleteModel(
            name='ReservaEquipamientoExtra',
        ),
    ]
