# Generated by Django 4.2.2 on 2023-07-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_reservaequipamiento_alter_equipamientoaula_aula_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipamientoDisponible',
            new_name='Equipamiento',
        ),
    ]
